language: r
cache: packages

branches:
  only: source
  
before_script:
  - sed -i 's/html_document/md_document/' docs/labs/R/*.Rmd

script:
  - Rscript -e 'servr:::knit_maybe(c(".", "_source", "_posts", "docs/labs/R"), c(".", "_posts", "_posts", "docs/labs/R"), "build.R", "jekyll")'
  - for f in docs/labs/R/*.Rmd; do printf -- '---\n' < ${f} > ${f/Rmd/Rmd2}; grep "^title:" < "${f}" >> "${f/Rmd/Rmd2}";printf -- 'layout: default\nparent: R\ngrand_parent: Labs\n---\n' < "${f/Rmd/Rmd2}" >> "${f/Rmd/Rmd2}"; cat "${f}" >> "${f/Rmd/Rmd2}";done
  - for f in docs/labs/R/*.Rmd2; do mv "${f}" "${f/Rmd2/Rmd}" # Only run this on TRAVIS-CI
  
latex: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: source
  target_branch: master
  
cache:
  - packages: true