#plugins:
#  - jekyll-remote-theme

#remote_theme: codeasashu/hcz-jekyll-blog

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Senanu's Bio class
email: senanu (at) gmail dot com
description: >- # this means to ignore newlines until "baseurl:"
  This site contains files and content for my Bio classes at
  Chaffey College and UCR
baseurl: /b40 # the subpath of your site, e.g. /blog
url: https://senanu.github.io # the base hostname & protocol for your site, e.g. http://example.com
incremental: true
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: jekyll-theme-slate
#theme: jekyll-theme-cayman
#theme: vsoch/docsy-jekyll
#theme: jekyll-theme-hyde
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Configurations for just-the-docs theme
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light

space00: '<input type="text" size="10" style="border-width: 0px;">'
space0: '<input type="text" size="30" style="border-width: 0px;">'
space1: '<textarea cols="100%" rows="1" style="border-width: 0px;"></textarea>'
space2: '<textarea cols="100%" rows="2" style="border-width: 0px;"></textarea>'
space3: '<textarea cols="100%" rows="3" style="border-width: 0px;"></textarea>'
space4: '<textarea cols="100%" rows="4" style="border-width: 0px;"></textarea>'
space5: '<textarea cols="100%" rows="5" style="border-width: 0px;"></textarea>'
space6: '<textarea cols="100%" rows="6" style="border-width: 0px;"></textarea>'
space7: '<textarea cols="100%" rows="7" style="border-width: 0px;"></textarea>'
space8: '<textarea cols="100%" rows="8" style="border-width: 0px;"></textarea>'
space9: '<textarea cols="100%" rows="9" style="border-width: 0px;"></textarea>'
space10: '<textarea cols="100%" rows="10" style="border-width: 0px;"></textarea>'
space11: '<textarea cols="100%" rows="11" style="border-width: 0px;"></textarea>'
space12: '<textarea cols="100%" rows="12" style="border-width: 0px;"></textarea>'
space13: '<textarea cols="100%" rows="13" style="border-width: 0px;"></textarea>'
space14: '<textarea cols="100%" rows="14" style="border-width: 0px;"></textarea>'
space15: '<textarea cols="100%" rows="15" style="border-width: 0px;"></textarea>'
space16: '<textarea cols="100%" rows="16" style="border-width: 0px;"></textarea>'
space17: '<textarea cols="100%" rows="17" style="border-width: 0px;"></textarea>'
space18: '<textarea cols="100%" rows="18" style="border-width: 0px;"></textarea>'
space19: '<textarea cols="100%" rows="19" style="border-width: 0px;"></textarea>'
space20: '<textarea cols="100%" rows="20" style="border-width: 0px;"></textarea>'
